### ISSUE TITLE
Another scaffolder/gapfiller

### ISSUE THREAD

**Issue by olekto** [schmeing/gapless-benchmark#1]
Hi,
have you seen SAMBA, another scaffolder/gapfiller? Here: https://github.com/alekseyzimin/masurca#samba-scaffolder

It's described here: https://www.biorxiv.org/content/10.1101/2021.10.21.465348v1

Sorry if it messes with your analyses for the paper, but I thought I'd mention it.

Ole

**Comment by schmeing** [comment]
Thank you for mentioning it. I will include it in the benchmark of course.
